version: "3.8"

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: linqumate-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data-volume:/var/lib/mysql
  api:
    build:
      context: ./api
    command: reflex -r '\.go$$' -s -- sh -c 'go run main.go' #reflexを使うことでgoのホットリロードを実現
    container_name: linqumate-api-server
    ports:
      - 1991:1991
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
      
  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: linqumate-migration
    volumes:
      - ./database/migration/schema:/flyway/sql




